### ISSUE TITLE
is there a way to playback binary data capured from m8 lidar(sockets not qview ) using qview?

### ISSUE THREAD

**Issue by sebastianhenaosanta** [QuanergySystems/quanergy_client#23]
i've been working with the m8 lidar in a raspberry pi, but i want to reproduce what i've captured. In that platfrom it's not possible to install qview, how can i reproduce my data?

**Comment by rossctaylor** [comment]
Are you wanting to use the SDK to record data and then see it with the SDK visualizer? The SDK doesn't have that functionality built in but it could be done.

To record, I'd start with the dynamic connection application because it doesn't require the PCL visualizer so would be easier to build on the Raspberry Pi. The raw packets are available here: https://github.com/QuanergySystems/quanergy_client/blob/master/apps/dynamic_connection.cpp#L151

You could just write them to disk instead of sending downstream to pipeline. I'd suggest buffering them and writing with a separate thread to reduce the likelihood of losing data.

To play back into the visualizer, you could make a loop that reads the data from disk and sends it to the pipeline in the visualizer instead of connecting the client: https://github.com/QuanergySystems/quanergy_client/blob/master/apps/visualizer.cpp#L165

Again, you might want to read on a thread, buffer, and slot the data on a separate thread. The packets are sent at about 1077 Hz so you'd need to slow things down a bit.

Let me know if this doesn't answer your question. Also, feel free to reach out to support@quanergy.com if you need more support.
